{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:12: AssertionError"}, "description": "this test fails", "start": 1637046538278, "stop": 1637046538280, "uuid": "9a4816bc-4aec-4600-a40e-7d93ecbb3fb3", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "suite", "value": "test_allure"}, {"name": "host", "value": "localhost"}, {"name": "thread", "value": "1260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}]}